### PR TITLE
Catch RemoteError in is_connected in BlueZ backend (#310)

### LINKED ISSUE #310: RemoteError when trying to disconnect
* bleak version: 0.8.0
* Python version: 3.7.3
* Operating System: Raspbian Buster
* BlueZ version (`bluetoothctl -v`) in case of Linux: 5.50

### Description

When trying to close the connection of a device the following `RemoteError` is raised on my Raspberry Pi Zero. I can see in the logs of the other device that the connection was properly closed though, so the error seems to be raised afterwards.
Same code works well on macOS. 

### What I Did

```
client = BleakClient(address)
await client.connect()
await client.disconnect()

Traceback (most recent call last):
  File "/home/pi/venv/lib/python3.7/site-packages/aioconsole/execute.py", line 87, in aexec
    result, new_local = await coro
  File "<aexec>", line 2, in __corofn
  File "/home/pi/venv/lib/python3.7/site-packages/bleak/backends/bluezdbus/client.py", line 245, in disconnect
    is_disconnected = not await self.is_connected()
  File "/home/pi/venv/lib/python3.7/site-packages/bleak/backends/bluezdbus/client.py", line 346, in is_connected
    ).asFuture(asyncio.get_event_loop())
txdbus.error.RemoteError: org.freedesktop.DBus.Error.UnknownObject: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
```

### PR DESCRIPTION
**Pull request by soldag**
Fixes #310

### CODE REVIEW

**Review by dlech — APPROVED** [review]
Looks good to me. Thanks!

**Comment by soldag** [comment]
Sorry, was too fast with creating this PR and there was still a bug in it 🙈

**Comment by dlech** [comment]
Good thing I didn't merge it right away. 😄  Looks even better now.

**Review by hbldh — APPROVED** [review]

**Comment by dlech** [comment]
Merged, thanks!

**Comment by soldag** [comment]
Any plan when this change will be released?

**Comment by hbldh** [comment]
I am planning on a small 0.8.1 release this week, with the several important fixes that are present in `develop` right now.

**Comment by soldag** [comment]
OK cool 👍

**Pull request merged**
