### PR TITLE
Adding a stop event in WinRT scanner

### PR DESCRIPTION
**Pull request by hbldh**
An alternate way of solving #556 and imo preferable to solving it by sacrificing the logging.

The stop event is originating from the Windows `BluetoothLEAdvertisementWatcher` class, so however the the scanning is stopped, it should generate an callback regardless of how it is stopped. This is, of course, you use the `BleakScanner`'s `start` method to initiate it...

### CODE REVIEW

**Comment by dlech** [comment]
This looks good to me. I assume we need the same fix in the dotnet backend?

**Comment by devanlai** [comment]
This fix looks good to me - it eliminates the race condition that I was using the reproduce the error in #556 and I've been running a test for a few minutes now running a scan with the WinRT backend every second for a few minutes now to stress test it and it seems fine.

**Comment by hbldh** [comment]
Good!

Ah, yes. The two backends. I will fix it in the morning.

**Comment by dlech** [comment]
Don't forget the changelog entry as we..

**Pull request merged**
