### PR TITLE
Ignore None type device address when using bdaddr

### PR DESCRIPTION
**Pull request by rrooggiieerr**
Pull Request Guidelines for Bleak
---------------------------------

Before you submit a pull request, check that it meets these guidelines:

1. If the pull request adds functionality, the docs should be updated.
2. Modify the `CHANGELOG.rst`, describing your changes as is specified by the
   guidelines in that document.
3. The pull request should work for Python 3.8+ on the following platforms:
    - Windows 10, version 16299 (Fall Creators Update) and greater
    - Linux distributions with BlueZ >= 5.43
    - OS X / macOS >= 10.11
4. Squash all your commits on your PR branch, if the commits are not solving
   different problems and you are committing them in the same PR. In that case,
   consider making several PRs instead.
5. Feel free to add your name as a contributor to the `AUTHORS.rst` file!

### CODE REVIEW

**Comment by dlech** [comment]
Did you decide this isn't needed after all or did you just get tired of waiting?

**Comment by rrooggiieerr** [comment]
I only get the 'NoneType' exception on my development MacBook and am currently not working on Bluetooth based integrations. My live system works on HAOS and thus doesn't have the problem.

So urgency isn't high for me, but it does solve a problem

**Comment by rrooggiieerr** [comment]
Ah, now I understand why you were asking. I removed a bunch of forked repositories including the bleak one which automatically closed this issue.

**Comment by dlech** [comment]
FYI, I can't merge or re-open the PR with the branch gone.

**Comment by rrooggiieerr** [comment]
OK, see #1539

**Pull request closed without merging**
