### PR TITLE
Fix for the 'Unknown' name in scan results on Windows 10. 

### PR DESCRIPTION
**Pull request by pjbosco**
Updated `BLEDevice` constructor to remove setting self.name to `Unknown` if not name. 
Updated `BLEDevice.__str__` conditional to check not self.name instead of equality to `Unknown` .
Updated second return statement in `BLEDevice.__str__` to use `self.name` or `Unknown`.

Updated changelog

### CODE REVIEW

**Comment by hbldh** [comment]
@pjbosco Looking good. However, this does not include the changes you proposed in #175; shouldn't that be added to this PR as well?

**Comment by pjbosco** [comment]
I found that changing the dotnet scanner.py was unnecessary given the changes to BLEDevice.__str__(). Essentially, the changes to scanner.py would have set BLEDevice.name itself to "Unknown" rather than simply allowing it to be None or empty string and dealing with the presentation in __str__(). I think the better approach is for BLEDevice.name to reflect physical reality; if we didn't find a name, we don't make the assumption that it is "Unknown".

**Comment by dlech** [comment]
I think this is a step in the right direction.

Perhaps getting a bit off topic, but on BlueZ, we can never get a name of `Unknown` since BlueZ will give the Bluetooth address as the name if there is no name. So to make things more consistent cross-platform, perhaps we should do the same here?

**Comment by hbldh** [comment]
It does? In that case, we should try to change the current `Unknown` default to that then.

**Comment by dlech** [comment]
> It does?

Yes, I noticed this when working on the `dbus-next-2` branch.

**Comment by pjbosco** [comment]
> It does? In that case, we should try to change the current `Unknown` default to that then.

Keep in mind, for the dotnet scanner to get and set the actual name from the ScanResponse `not BLEDevice.name` must resolve to `True`. If we set BLEDevice.name to anything that breaks that resolution in BLEDevice constructor, dotnet scanner will never set the correct name. 

See https://github.com/pjbosco/bleak/blob/cb8fd75821bb87013ce15ffd86bceccc093d67f2/bleak/backends/dotnet/scanner.py#L212

Perhaps if the ScanResponse does not have a local name, set name to the bluetooth address.
For example the following:
```
            if (
                not new_device.name
                and event_args.BluetoothAddress in self._scan_responses
            ):
                new_device.name = self._scan_responses[
                    event_args.BluetoothAddress
                ].Advertisement.LocalName
```

Would become:
```
            if (
                not new_device.name
                and event_args.BluetoothAddress in self._scan_responses
            ):
                new_device.name = self._scan_responses[
                    event_args.BluetoothAddress
                ].Advertisement.LocalName or event_args.BluetoothAddress
```

I think this would solve the broken windows behavior while bringing the behavior in line with BlueZ.

**Pull request merged**
