### PR TITLE
Fix Hanging on "async with BleakClient..." on OSX

### PR DESCRIPTION
**Pull request by ShaharHD**
Fix for issue #116

### CODE REVIEW

**Comment by hbldh** [comment]
I just saw the changes in #209, which solves this issue in another way, which I think will yield an even better result in the end. Thank you for the PR though! I will close this and if #209 does not solve the same issue, we will ahve to revisit this later on.

**Comment by ShaharHD** [comment]
@hbldh Why not incorporate the fix right now (It is a limited fix, specific to OS X)? 

And once #209 PR (which is huge) is completed, it will overwrite this fix?

Right now - every time I install Bleak, I need to have a script to manually patch it.

**Comment by hbldh** [comment]
Because I have no desire to make two releases so close to each other. There will be one next week, so I will wait until then.

It is not unusable on macOS. I used it just fine a minute ago.

**Comment by ShaharHD** [comment]
Look at comments of the other users on #116 which confirms my fix works...

**Comment by ShaharHD** [comment]
> It is not unusable on macOS. I used it just fine a minute ago.

Be aware you were not able to reproduce the issue last year as well.

**Comment by hbldh** [comment]
I have merged #227 into `develop` and will make a version 0.7.0 release later today with those changes as well as a lot of others. If the "fire twice" problem is still left after release of version 0.7.0, I will include these changes in a version 0.7.X release tomorrow.

**Pull request closed without merging**
